/* Public template: bind :business_date; never concatenate user input. */
SELECT
    ACCESSION_NUMBER,
    PATIENT_IDENTIFIER,
    ORDER_CREATION_DATE,
    EXAM_START_DATE,
    EXAM_END_DATE,
    REPORT_START_DATE,
    REPORT_FINAL_DATE,
    MODALITY,
    EXAM_DESCRIPTION,
    FACILITY,
    DEPARTMENT,
    PATIENT_TYPE,
    PRIORITY_LEVEL,
    ORDERING_SERVICE,
    ORDERING_PROVIDER,
    RADIOLOGIST,
    STATUS,
    TURNAROUND_MINUTES,
    SOURCE_SYSTEM,
    LOAD_REFERENCE
FROM APPROVED_REPORTING_VIEW
WHERE ORDER_CREATION_DATE >= :business_date
  AND ORDER_CREATION_DATE < :business_date + 1
